---
rootfs:
  suite: trixie
  mirror: http://deb.debian.org/debian
ostree:
  branch: debian/trixie
  repo: ostree_repo
  template: debian-ostree-commit.yaml
image:
  name: debian-ostree-qemu-uefi-amd64.img
  size: 20G
  template: debian-ostree-amd64.yaml
