---
rootfs:
  suite: bookworm
  mirror: http://ftp.ca.debian.org/debian
  packages:
    - task-mate-desktop
    - task-desktop
    - firefox-esr
ostree:
  branch: debian/bookworm-desktop
  repo: ostree_repo
  template: debian-ostree-commit.yaml
image:
  name: debian-ostree-qemu-uefi-amd64.img
  size: 80G
  template: debian-ostree-amd64.yaml
